#!/usr/bin/env -iS /opt/pwn.college/bash

set -e
PATH=/bin
chmod 000 /opt/pwn.college
mount --bind / /
mount -o remount,nosuid /

umask 377
PASSWORD=$RANDOM$RANDOM$RANDOM$RANDOM
echo $PASSWORD > /challenge/password

read FLAG </flag
rm /flag
chmod u+s /usr/bin/mv

read RESPONSE
if [ "$PASSWORD" == "$RESPONSE" ]
then
	echo $FLAG
fi
