#!/usr/bin/env -iS /opt/pwn.college/bash

set -e
PATH=/bin

mount --bind /nix /nix
mount -o remount,nosuid /nix
mount --bind /opt/pwn.college /opt/pwn.college
mount -o remount,nosuid /opt/pwn.college
rm -f /usr/bin/exec-suid /challenge/run

umask 377
PASSWORD=$RANDOM$RANDOM$RANDOM$RANDOM
echo $PASSWORD > /challenge/password

read FLAG </flag
rm /flag
chmod u+s /usr/bin/mv

echo "Password:"
read RESPONSE
if [ "$PASSWORD" == "$RESPONSE" ]
then
	echo $FLAG
fi
