#!/usr/bin/env -iS /opt/pwn.college/bash

PATH=/usr/bin

rm -f /challenge/vault
echo "The secret is: " > /challenge/vault
read SRC < <(head -n 1 | tr -cd "[a-z0-9/]")

chmod 000 /challenge/vault
cat $SRC >> /challenge/vault
