#!/usr/bin/env -iS /opt/pwn.college/bash

# let's see if White can cheese this one ;-)

set -e
PATH=/bin

mkdir -p /tmp/empty
mount --bind /tmp/empty /nix
mount --bind /tmp/empty /opt/pwn.college
mount --bind /tmp/empty /home
rm -f /usr/bin/exec-suid /challenge/run

umask 377
PASSWORD=$RANDOM$RANDOM$RANDOM$RANDOM
echo $PASSWORD > /challenge/password

read FLAG </flag
rm /flag
chmod u+s /usr/bin/mv

echo "Password:"
read RESPONSE
if [ "$PASSWORD" == "$RESPONSE" ]
then
	echo $FLAG
fi
