#!/usr/bin/env -iS /opt/pwn.college/bash

PATH=/usr/bin

WORKDIR=$(mktemp -d)
[ -n "$WORKDIR" ] || exit 2
cd $WORKDIR

cp -a "$1" catbomb
[ -f catbomb ] || exit 3
cat catbomb > detonated

read SIZE_PRE _ < <(du -sm catbomb)
read SIZE_POST _ < <(du -sm detonated)
[ "$SIZE_PRE" -lt "$SIZE_POST" ] && cat /flag
